ContactManager.Panel/Models/ErrorViewModel.cs
using System;

namespace ContactManager.Panel.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ContactManager.Panel/Controllers/AccountController.cs
using DataTransferObject.Shared;
using DataTransferObject.User;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using RestSharp;

namespace ContactManager.Panel.Controllers
{
    [EnableCors("panel")]
    public class AccountController : Controller
    {
        private readonly IConfiguration _configuration;
        public AccountController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(LoginRequestDto requestDto)
        {
            var client = new RestClient(_configuration["Api:Url"] + "Account/login");
            var request = new RestRequest(Method.POST);
            request.RequestFormat = DataFormat.Json;
            request.AddJsonBody(new LoginRequestDto
            {
                Password = requestDto.Password,
                PhoneNumber = requestDto.PhoneNumber
            });
            var response = client.Execute<ResponseDto<LoginDto>>(request);
            HttpContext.Session.SetString("JWToken", response.Data.Response.Token);
            HttpContext.Session.SetString("Role", response.Data.Response.Role);

            return RedirectToAction("Index", "Home");
        }
    }
}

ContactManager.Panel/Controllers/ContactController.cs
using System.Threading.Tasks;
using DataTransferObject.Commands.Contact;
using DataTransferObject.Queries.Contact;
using DataTransferObject.Shared;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using RestSharp;
using RestSharp.Authenticators;

namespace ContactManager.Panel.Controllers
{
    public class ContactController : Controller
    {
        private readonly IConfiguration _configuration;
        public ContactController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public async Task<IActionResult> Index()
        {
            var client = new RestClient(_configuration["Api:Url"] + "contact/index");
            var request = new RestRequest(Method.GET);
            request.RequestFormat = DataFormat.Json;
            var token = HttpContext.Session.GetString("JWToken");
            client.Authenticator = new JwtAuthenticator(token);
            var response = await client.ExecuteAsync<ListResponseDto<ContactListDto>>(request);
            return View(response.Data.List);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromBody] AddContactRequestDto requestDto)
        {
            var client = new RestClient(_configuration["Api:Url"] + "contact/create");
            var request = new RestRequest(Method.POST);
            request.RequestFormat = DataFormat.Json;
            var token = HttpContext.Session.GetString("JWToken");
            client.Authenticator = new JwtAuthenticator(token);
            request.AddHeader("contentType", "application/json; charset=utf-8");
            request.AddJsonBody(requestDto);
            var response = await client.ExecuteAsync<ResponseDto>(request);
            return Json(response.Data);
        }
    }
}

ContactManager.Panel/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ContactManager.Panel.Models;
using Microsoft.AspNetCore.Authorization;
using Common.Attributes;
using DataTransferObject.Enums;

namespace ContactManager.Panel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ContactManager.Panel/Controllers/UserController.cs
using System.Threading.Tasks;
using DataTransferObject.Queries.User;
using DataTransferObject.Shared;
using DataTransferObject.User;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using RestSharp;
using RestSharp.Authenticators;

namespace ContactManager.Panel.Controllers
{
    public class UserController : Controller
    {
        private readonly IConfiguration _configuration;
        public UserController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IActionResult> Index(ListRequestDto<UserListDto> requestDto)
        {
            var client = new RestClient(_configuration["Api:Url"] + "user/index");
            var request = new RestRequest(Method.GET);
            request.RequestFormat = DataFormat.Json;
            var token = HttpContext.Session.GetString("JWToken");
            client.Authenticator = new JwtAuthenticator(token);
            var response = await client.ExecuteAsync<ListResponseDto<UserListDto>>(request);
            return View(response.Data.List);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([FromBody] UserAddRequestDto requestDto)
        {
            var client = new RestClient(_configuration["Api:Url"] + "user/create");
            var request = new RestRequest(Method.POST);
            request.RequestFormat = DataFormat.Json;
            var token = HttpContext.Session.GetString("JWToken");
            client.Authenticator = new JwtAuthenticator(token);
            request.AddHeader("contentType", "application/json; charset=utf-8");
            request.AddJsonBody(requestDto);
            var response = await client.ExecuteAsync<ResponseDto>(request);
            return Json(response.Data);
        }
    }
}

ContactManager.Panel/Views/Contact/Create.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

@{
    ViewData["Title"] = "اجاد مخاطب";
}
<div class="text-center">
    <h1>ایجاد مخاطب</h1>


    <hr />
    <div class="row justify-content-center">
        <div class="col-md-4">
            <section class="create-contact">
                <form class="create-contact">
                    <div class="form-group">
                        <label class="control-label"> نام</label>
                        <input name="FirstName" class="form-control" />
                        <span class="first-name text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">نام خانوادگی</label>
                        <input name="LastName" class="form-control" />
                        <span class="last-name text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">موبایل</label>
                        <input name="PhoneNumber" class="form-control" />
                        <span class="phoneNumber text-danger"></span>
                    </div>
                    <div class="form-group">
                        <button class="create-contact btn btn-primary"> ثبت </button>
                    </div>
                </form>
            </section>
        </div>
    </div>
</div>




@section Scripts {
    <script src="~/js/Contact/create-contact.js"></script>
    <script>

        $(document).ready(function () {
            $("section.create-contact").createContact({
                ApiUrl: "@Configuration["Api:Url"]"
            });
        });

    </script>

}

ContactManager.Panel/Views/Contact/Index.cshtml
@model IEnumerable<DataTransferObject.Queries.Contact.ContactListDto>

@{
    ViewData["Title"] = "لیست مخاطبین";
}


    <div style="margin:5px">
        <a class="btn btn-info" asp-action="Create">ایجاد مخاطب</a>

    </div>

<table class="table table-bordered table-hover table-striped  text-center">
    <thead class="thead-dark">
        <tr>
            <th>
                نام
            </th>
            <th>
                نام خانوادگی
            </th>
            <th>
                موبایل
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
            </tr>
        }
    </tbody>
</table>

ContactManager.Panel/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "صفحه اصلی ";
}

ContactManager.Panel/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Http;
@using DataTransferObject.Enums
@{
    var identityCliams = User.Identity as ClaimsIdentity;
    var role = Context.Session.GetString("Role");
    var panelName = "";
    switch (role)
    {
        case nameof(UserType.Manager):
            panelName = "مدیریت کاربران";
            break;
        case nameof(UserType.User):
            panelName = "مدیریت مخاطبین";
            break;
        default:
            break;
    }

}
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContactManager.Panel</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@panelName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">خانه</a>
                        </li>
                        
                        <li>
                            @{
                                if (role == nameof(UserType.Manager))
                                {
                                    <div class="dropdown">
                                        <button class="btn  dropdown-toggle" type="button" data-toggle="dropdown">
                                            کاربران
                                            <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Create">ایجاد</a>
                                            </li>
                                            <li>
                                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">لیست</a>
                                            </li>
                                        </ul>
                                    </div>
                                }
                                if (role == nameof(UserType.User))
                                {
                                    <div class="dropdown">
                                        <button class="btn  dropdown-toggle" type="button" data-toggle="dropdown">
                                            مخاطبین
                                            <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu">
                                            <li>
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Create">ایجاد</a>
                                            </li>
                                            <li>
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">لیست</a>
                                            </li>
                                        </ul>
                                    </div>
                                }
                            }
                        </li>

                        <li class="nav-item">
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ContactManager.Panel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ContactManager.Panel/Views/User/Create.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

@{
    ViewData["Title"] = "Create";
}
<div class="text-center">
    <h1>ایجاد کاربر</h1>


    <hr />
    <div class="row justify-content-center">
        <div class="col-md-4">
            <section class="create-user">
                <form class="create-user">
                    <div class="form-group">
                        <label class="control-label"> نام</label>
                        <input name="FirstName" class="form-control" />
                        <span class="first-name text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">نام خانوادگی</label>
                        <input name="LastName" class="form-control" />
                        <span class="last-name text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">موبایل</label>
                        <input name="PhoneNumber" class="form-control" />
                        <span class="phoneNumber text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">ایمیل</label>
                        <input name="Email" class="form-control" />
                        <span class="email"></span>
                    </div>
                    <div class="form-group">
                        <label class="control-label">رمز عبور</label>
                        <input name="Password" class="form-control" />
                        <span class="password text-danger"></span>
                    </div>
                    <div class="form-group">
                        <button class="create-user btn btn-primary"> ثبت </button>
                    </div>
                </form>
            </section>
        </div>
    </div>
</div>




@section Scripts {
    <script src="~/js/User/create-user-contact.js"></script>
    <script>

        $(document).ready(function () {
            $("section.create-user").createUserContact({
                ApiUrl: "@Configuration["Api:Url"]"
            });
        });

    </script>

}

ContactManager.Panel/Views/User/Index.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration
@model IEnumerable<DataTransferObject.Queries.User.UserListDto>

@{
    ViewData["Title"] = "لیست کاربران";
}


<div style="margin:5px">
    <a class="btn btn-info" asp-action="Create">ایجاد کاربر</a>

</div>

<table class="table table-bordered table-hover table-striped  text-center">
    <thead class="thead-dark">
        <tr>
            <th>
                نام
            </th>
            <th>
                نام خانوادگی
            </th>
            <th>
                موبایل
            </th>
            <th>
                ایمیل

            </th>
            <th>
                تنظیمات

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    <button class="btn btn-danger remove-user" title="حذف کاربر"><i class="fas fa-trash"></i></button>
                </td>
            </tr>
        }
    </tbody>
</table>